name: Fetch GitHub User Info

# on:
#   schedule:
#     - cron: '0 0 * * *' # 한국시간 오전 9시에 실행

# 이후 데이터 업데이트 필요시 cron 수정
on:
  push:
    branches:
      - main

jobs:
  fetch-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      env:
        github_actor: ${{ github.actor }}
      run: python user_info.py

# Git Push
    - name: Commit and push changes
      run: |
        git config --local user.email "pozuhtuhv@gmail.com"
        git config --local user.name "Hyeonseok-Cho"
        git add -A
        git commit -m "(update) auto_svg_data"
        git push
