name: Fetch GitHub User Info

on:
  push:
    branches:
      - main

jobs:
  fetch-info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
          
    - name: Fetch GitHub Actor Info
      run: |
        echo "GITHUB_ACTOR=${{ github.actor }}" >> $GITHUB_ENV
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python script
      run: python user_info.py
